### ISSUE TITLE
[PATCH] spelling fix

### ISSUE THREAD

**Issue by gregoa** [lestrrat/DateTime-Format-Pg#10]
In Debian we are currently applying the following patch to
DateTime-Format-Pg.
We thought you might be interested in it too.

    Description: spelling fix
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-07-20
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libdatetime-format-pg-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by lestrrat** [comment]
I knew you Debian folks take your libraries seriously, but I did not expect to see you guys keep track of spelling errors, too! :D
