### ISSUE TITLE
parse_duration not handling fractions of a second.

### ISSUE THREAD

**Issue by yewtc** [lestrrat/DateTime-Format-Pg#12]
V 0.16012, OS Fedora 23 perl 5.22.1

As it says. DateTime::Format::Pg->parse_duration('1095 days 13:37:28.369224') results in 
Unknown timespec: 1095 days 13:37:28.369224. Under the debugger it looks like it's the .369224 bit that it is complaining about. ( It might have been clearer if I could have seen that more directly in the error message).

It looks like the code around lines 593-596 is not taking fractional seconds into account.

**Comment by lestrrat** [comment]
can you please provide a failing test?

**Comment by yewtc** [comment]
I tried to upload the file, but I couldn't upload a *.t file.  (This passes at 0.160011).

####
#!/usr/bin/env perl
#
use strict;
use warnings;

use Test::More;
use Test::Exception;

BEGIN {
    use_ok('DateTime::Format::Pg');
};

my $offset = '1095 days 13:37:28.369224';

my $duration;
lives_ok {
    $duration = DateTime::Format::Pg->parse_duration($offset);
} "Lives ok";


done_testing;
