### ISSUE TITLE
Amountless units don't croak

### ISSUE THREAD

**Issue by ralesk** [lestrrat/DateTime-Format-Pg#8]
Apparently if you forget to supply an amount to a unit, `parse_duration` will happily create a 0 duration object.

```
my $duration = DateTime::Format::Pg->parse_interval("2 hello"); ## dies with Unknown timespec
my $duration2 = DateTime::Format::Pg->parse_interval("hello"); ## Contains a 0 duration
my $duration3 = DateTime::Format::Pg->parse_interval("-days"); ## Contains a 0 duration 
```

**Comment by christopherraa** [comment]
This was introduced between `DateTime-Format-Pg-0.16009` (*working as expected*) and `DateTime-Format-Pg-0.16011` (*not working as expected*).

**Comment by lestrrat** [comment]
Apologies, had not noticed this issue :/

**Comment by lestrrat** [comment]
@ralesk @christopherraa can you please check the above PR?
